Scc 2914
NYPL/discovery-api pull request #234
Opened 2022-03-28 16:39 UTC by charmingduchess

This work is to make sure that the parallel fields backend work ends up in the discovery api response body. I added a function, parallelFieldsExtractor, that is now called in the response massager. The function extracts the individual parallel fields on the bib record and deletes the array where it got those fields from.

2022-03-28 19:30 UTC, nonword requested changes

2022-03-28 19:30 UTC, nonword commented on lib/parallel-fields-extractor.js
> +        bib._source[`parallel${capitalizedFieldName}`] = [field['@value']]
We need to check the `.index` vaue. If `field.index` is `3`, we actually want the value to be stored at index 3. So something like
```bib._source[`parallel${capitalizedFieldName}`][field.index] = field['@value']``` (after initializing as an array if it's not already initialized)

2022-03-29 14:35 UTC, charmingduchess commented on lib/parallel-fields-extractor.js
> +  elasticSearchResponse.hits.hits = updatedHits
I'm happy to make those changes. I think I did it like this because other functions called in the response massager had a similar approach.

2022-03-29 18:58 UTC, nonword approved these changes

2022-03-29 19:04 UTC, merged